modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL="https://github.com/mlus-asuka/RePortality/issues"

authors = "buuz135,mlus"
[[mods]]
modId = "portality"
version="${file.jarVersion}"
displayName = "Portality"
description = '''
Thinkig through portals
'''
[[dependencies.portality]]
modId = "forge"
mandatory = true
versionRange = "[47.1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.portality]]
modId = "titanium"
mandatory = true
versionRange = "[3.8.0,)"
ordering = "NONE"
side = "BOTH"